### ISSUE TITLE
How to enable Alerting?

### ISSUE THREAD

**Issue by Jeeppler** [awsdocs/amazon-elasticsearch-service-developer-guide#16]
According to the release notes, update [R20190221](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html) introduces alerting. The alerting feature even has a page in the [documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/alerting.html).

However, when I start a new ElasticSearch Service 6.42 instance with update R20190221 in N. Virgina and access Kibana I am unable to see a new section called Alerting in the UI. Am I missing something here?

Would it be possible to include a screen shot to show how the Alerting feature can be choosen?

**Comment by aetter** [comment]
Hi @Jeeppler, can you confirm that you're running R20190221 in us-east-1? I just created a new domain in the region and am on R20190113. My understanding is that we're yet to roll out the new service software to all regions.

Features that we add to Kibana will roll out incrementally rather than on a given launch day, and we probably won't announce them in a What's New post/on social media until they're available everywhere.

If you're anxious to test the new feature, I can confirm that it's available in eu-west-3 (Paris).

**Comment by Jeeppler** [comment]
Sorry, I got confused. N. Virginia has only R20190113 version available. Thanks for the clarification.
