### ISSUE TITLE
No mention of the latest R20200910 SSR in the release notes

### ISSUE THREAD

**Issue by sbocinec** [awsdocs/amazon-elasticsearch-service-developer-guide#33]
The latest available `R20200910` SSR is being offered for update for an ES instance in `us-east-1`, though the [release notes doc](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html#release-table) does not mention this release. 

Can you please update the doc, so we know what is being delivered by the update?

I see, this is pretty common issue being reported often by customers. Is there any chance to improve the release process to improve the customer experience and ensure, the release notes doc is updated on time?

**Comment by aetter** [comment]
Service software updates typically arrive a bit before their associated new features, so as their features arrive, we try to note the minimum required service software version, which you can see on that page for R20200910. Otherwise, the updates are some mix of bug fixes, improvements, and security updates (typically library bumps) that we don't go into further detail on.
